//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.36213
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBrCode_View.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WebSDataBrUpdater", ConfigurationName="ServiceReference2.WebSDataBrUpdaterSoap")]
    public interface WebSDataBrUpdaterSoap {
        
        // CODEGEN: Параметр "System_Get_ReleaseResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrUpdater/System_Get_Release", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataBrCode_View.ServiceReference2.System_Get_ReleaseResponse System_Get_Release(DataBrCode_View.ServiceReference2.System_Get_ReleaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrUpdater/System_Get_Release", ReplyAction="*")]
        System.Threading.Tasks.Task<DataBrCode_View.ServiceReference2.System_Get_ReleaseResponse> System_Get_ReleaseAsync(DataBrCode_View.ServiceReference2.System_Get_ReleaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrUpdater/GetLogTSD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLogTSD();
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrUpdater/GetLogTSD", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetLogTSDAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="System_Get_Release", WrapperNamespace="WebSDataBrUpdater", IsWrapped=true)]
    public partial class System_Get_ReleaseRequest {
        
        public System_Get_ReleaseRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="System_Get_ReleaseResponse", WrapperNamespace="WebSDataBrUpdater", IsWrapped=true)]
    public partial class System_Get_ReleaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrUpdater", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] System_Get_ReleaseResult;
        
        public System_Get_ReleaseResponse() {
        }
        
        public System_Get_ReleaseResponse(byte[] System_Get_ReleaseResult) {
            this.System_Get_ReleaseResult = System_Get_ReleaseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebSDataBrUpdaterSoapChannel : DataBrCode_View.ServiceReference2.WebSDataBrUpdaterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebSDataBrUpdaterSoapClient : System.ServiceModel.ClientBase<DataBrCode_View.ServiceReference2.WebSDataBrUpdaterSoap>, DataBrCode_View.ServiceReference2.WebSDataBrUpdaterSoap {
        
        public WebSDataBrUpdaterSoapClient() {
        }
        
        public WebSDataBrUpdaterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebSDataBrUpdaterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSDataBrUpdaterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSDataBrUpdaterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataBrCode_View.ServiceReference2.System_Get_ReleaseResponse DataBrCode_View.ServiceReference2.WebSDataBrUpdaterSoap.System_Get_Release(DataBrCode_View.ServiceReference2.System_Get_ReleaseRequest request) {
            return base.Channel.System_Get_Release(request);
        }
        
        public byte[] System_Get_Release() {
            DataBrCode_View.ServiceReference2.System_Get_ReleaseRequest inValue = new DataBrCode_View.ServiceReference2.System_Get_ReleaseRequest();
            DataBrCode_View.ServiceReference2.System_Get_ReleaseResponse retVal = ((DataBrCode_View.ServiceReference2.WebSDataBrUpdaterSoap)(this)).System_Get_Release(inValue);
            return retVal.System_Get_ReleaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataBrCode_View.ServiceReference2.System_Get_ReleaseResponse> DataBrCode_View.ServiceReference2.WebSDataBrUpdaterSoap.System_Get_ReleaseAsync(DataBrCode_View.ServiceReference2.System_Get_ReleaseRequest request) {
            return base.Channel.System_Get_ReleaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataBrCode_View.ServiceReference2.System_Get_ReleaseResponse> System_Get_ReleaseAsync() {
            DataBrCode_View.ServiceReference2.System_Get_ReleaseRequest inValue = new DataBrCode_View.ServiceReference2.System_Get_ReleaseRequest();
            return ((DataBrCode_View.ServiceReference2.WebSDataBrUpdaterSoap)(this)).System_Get_ReleaseAsync(inValue);
        }
        
        public System.Data.DataTable GetLogTSD() {
            return base.Channel.GetLogTSD();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetLogTSDAsync() {
            return base.Channel.GetLogTSDAsync();
        }
    }
}
