//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.5477
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.CompactFramework.Design.Data, версия: 2.0.50727.5477.
// 
namespace DataBrUpdater.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebSDataBrUpdaterSoap", Namespace="WebSDataBrUpdater")]
    public partial class WebSDataBrUpdater : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WebSDataBrUpdater() {
            this.Url = "http://192.168.80.15:27078/websdatabrupdater.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrUpdater/System_Get_Release", RequestNamespace="WebSDataBrUpdater", ResponseNamespace="WebSDataBrUpdater", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] System_Get_Release() {
            object[] results = this.Invoke("System_Get_Release", new object[0]);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSystem_Get_Release(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("System_Get_Release", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndSystem_Get_Release(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
    }
}
