//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingService.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WebSDataBrCode", ConfigurationName="ServiceReference1.WebSDataBrCodeSoap")]
    public interface WebSDataBrCodeSoap {
        
        // CODEGEN: Контракт генерации сообщений с сообщением GetServerDataTimeRequest имеет заголовки.
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/GetServerDataTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestingService.ServiceReference1.GetServerDataTimeResponse GetServerDataTime(TestingService.ServiceReference1.GetServerDataTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/GetServerDataTime", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.GetServerDataTimeResponse> GetServerDataTimeAsync(TestingService.ServiceReference1.GetServerDataTimeRequest request);
        
        // CODEGEN: Контракт генерации сообщений с сообщением FixedWeightRequest имеет заголовки.
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/FixedWeight", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestingService.ServiceReference1.FixedWeightResponse FixedWeight(TestingService.ServiceReference1.FixedWeightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/FixedWeight", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.FixedWeightResponse> FixedWeightAsync(TestingService.ServiceReference1.FixedWeightRequest request);
        
        // CODEGEN: Контракт генерации сообщений с сообщением Test_ConnectRequest имеет заголовки.
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/Test_Connect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestingService.ServiceReference1.Test_ConnectResponse Test_Connect(TestingService.ServiceReference1.Test_ConnectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/Test_Connect", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.Test_ConnectResponse> Test_ConnectAsync(TestingService.ServiceReference1.Test_ConnectRequest request);
        
        // CODEGEN: Контракт генерации сообщений с сообщением Test_LoginRequest имеет заголовки.
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/Test_Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestingService.ServiceReference1.Test_LoginResponse Test_Login(TestingService.ServiceReference1.Test_LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/Test_Login", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.Test_LoginResponse> Test_LoginAsync(TestingService.ServiceReference1.Test_LoginRequest request);
        
        // CODEGEN: Контракт генерации сообщений с сообщением POST_EU_LIST_WarehouseRequest имеет заголовки.
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/POST_EU_LIST_Warehouse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestingService.ServiceReference1.POST_EU_LIST_WarehouseResponse POST_EU_LIST_Warehouse(TestingService.ServiceReference1.POST_EU_LIST_WarehouseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/POST_EU_LIST_Warehouse", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_LIST_WarehouseResponse> POST_EU_LIST_WarehouseAsync(TestingService.ServiceReference1.POST_EU_LIST_WarehouseRequest request);
        
        // CODEGEN: Контракт генерации сообщений с сообщением POST_EU_TASK_MOVERequest имеет заголовки.
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/POST_EU_TASK_MOVE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestingService.ServiceReference1.POST_EU_TASK_MOVEResponse POST_EU_TASK_MOVE(TestingService.ServiceReference1.POST_EU_TASK_MOVERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/POST_EU_TASK_MOVE", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_TASK_MOVEResponse> POST_EU_TASK_MOVEAsync(TestingService.ServiceReference1.POST_EU_TASK_MOVERequest request);
        
        // CODEGEN: Контракт генерации сообщений с сообщением POST_EU_IN_AGRRequest имеет заголовки.
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/POST_EU_IN_AGR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestingService.ServiceReference1.POST_EU_IN_AGRResponse POST_EU_IN_AGR(TestingService.ServiceReference1.POST_EU_IN_AGRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/POST_EU_IN_AGR", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_IN_AGRResponse> POST_EU_IN_AGRAsync(TestingService.ServiceReference1.POST_EU_IN_AGRRequest request);
        
        // CODEGEN: Контракт генерации сообщений с сообщением POST_EU_LIST_SHIPRequest имеет заголовки.
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/POST_EU_LIST_SHIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestingService.ServiceReference1.POST_EU_LIST_SHIPResponse POST_EU_LIST_SHIP(TestingService.ServiceReference1.POST_EU_LIST_SHIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/POST_EU_LIST_SHIP", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_LIST_SHIPResponse> POST_EU_LIST_SHIPAsync(TestingService.ServiceReference1.POST_EU_LIST_SHIPRequest request);
        
        // CODEGEN: Контракт генерации сообщений с сообщением POST_EU_LIST_RZDN_AGRRequest имеет заголовки.
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/POST_EU_LIST_RZDN_AGR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestingService.ServiceReference1.POST_EU_LIST_RZDN_AGRResponse POST_EU_LIST_RZDN_AGR(TestingService.ServiceReference1.POST_EU_LIST_RZDN_AGRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/POST_EU_LIST_RZDN_AGR", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_LIST_RZDN_AGRResponse> POST_EU_LIST_RZDN_AGRAsync(TestingService.ServiceReference1.POST_EU_LIST_RZDN_AGRRequest request);
        
        // CODEGEN: Контракт генерации сообщений с сообщением POST_EU_LIST_INVERT_MXRequest имеет заголовки.
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/POST_EU_LIST_INVERT_MX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestingService.ServiceReference1.POST_EU_LIST_INVERT_MXResponse POST_EU_LIST_INVERT_MX(TestingService.ServiceReference1.POST_EU_LIST_INVERT_MXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/POST_EU_LIST_INVERT_MX", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_LIST_INVERT_MXResponse> POST_EU_LIST_INVERT_MXAsync(TestingService.ServiceReference1.POST_EU_LIST_INVERT_MXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/GetLogTSD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLogTSD();
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/GetLogTSD", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetLogTSDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/GetLogTSDOnline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLogTSDOnline();
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/GetLogTSDOnline", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetLogTSDOnlineAsync();
        
        // CODEGEN: Контракт генерации сообщений с сообщением DataBase_Clone_SQLiteZipFileRequest имеет заголовки.
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/DataBase_Clone_SQLiteZipFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestingService.ServiceReference1.DataBase_Clone_SQLiteZipFileResponse DataBase_Clone_SQLiteZipFile(TestingService.ServiceReference1.DataBase_Clone_SQLiteZipFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/DataBase_Clone_SQLiteZipFile", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.DataBase_Clone_SQLiteZipFileResponse> DataBase_Clone_SQLiteZipFileAsync(TestingService.ServiceReference1.DataBase_Clone_SQLiteZipFileRequest request);
        
        // CODEGEN: Параметр "System_Get_ReleaseResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/System_Get_Release", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestingService.ServiceReference1.System_Get_ReleaseResponse System_Get_Release(TestingService.ServiceReference1.System_Get_ReleaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/System_Get_Release", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.System_Get_ReleaseResponse> System_Get_ReleaseAsync(TestingService.ServiceReference1.System_Get_ReleaseRequest request);
        
        // CODEGEN: Контракт генерации сообщений с сообщением TestLogRequest имеет заголовки.
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/TestLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestingService.ServiceReference1.TestLogResponse TestLog(TestingService.ServiceReference1.TestLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/TestLog", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.TestLogResponse> TestLogAsync(TestingService.ServiceReference1.TestLogRequest request);
        
        // CODEGEN: Контракт генерации сообщений с сообщением SAVE_LOG_TSD_ZIPRequest имеет заголовки.
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/SAVE_LOG_TSD_ZIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestingService.ServiceReference1.SAVE_LOG_TSD_ZIPResponse SAVE_LOG_TSD_ZIP(TestingService.ServiceReference1.SAVE_LOG_TSD_ZIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/SAVE_LOG_TSD_ZIP", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.SAVE_LOG_TSD_ZIPResponse> SAVE_LOG_TSD_ZIPAsync(TestingService.ServiceReference1.SAVE_LOG_TSD_ZIPRequest request);
        
        // CODEGEN: Контракт генерации сообщений с сообщением CHECK_CLIENT_VERSIONRequest имеет заголовки.
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/CHECK_CLIENT_VERSION", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestingService.ServiceReference1.CHECK_CLIENT_VERSIONResponse CHECK_CLIENT_VERSION(TestingService.ServiceReference1.CHECK_CLIENT_VERSIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebSDataBrCode/CHECK_CLIENT_VERSION", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.CHECK_CLIENT_VERSIONResponse> CHECK_CLIENT_VERSIONAsync(TestingService.ServiceReference1.CHECK_CLIENT_VERSIONRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="WebSDataBrCode")]
    public partial class BrHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passwordField;
        
        private string macAdressField;
        
        private string dnsAdressField;
        
        private string clientVersionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("Login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MacAdress {
            get {
                return this.macAdressField;
            }
            set {
                this.macAdressField = value;
                this.RaisePropertyChanged("MacAdress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DnsAdress {
            get {
                return this.dnsAdressField;
            }
            set {
                this.dnsAdressField = value;
                this.RaisePropertyChanged("DnsAdress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ClientVersion {
            get {
                return this.clientVersionField;
            }
            set {
                this.clientVersionField = value;
                this.RaisePropertyChanged("ClientVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServerDataTime", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class GetServerDataTimeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="WebSDataBrCode")]
        public TestingService.ServiceReference1.BrHeader BrHeader;
        
        public GetServerDataTimeRequest() {
        }
        
        public GetServerDataTimeRequest(TestingService.ServiceReference1.BrHeader BrHeader) {
            this.BrHeader = BrHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServerDataTimeResponse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class GetServerDataTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public System.DateTime GetServerDataTimeResult;
        
        public GetServerDataTimeResponse() {
        }
        
        public GetServerDataTimeResponse(System.DateTime GetServerDataTimeResult) {
            this.GetServerDataTimeResult = GetServerDataTimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FixedWeight", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class FixedWeightRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="WebSDataBrCode")]
        public TestingService.ServiceReference1.BrHeader BrHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public string label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=1)]
        public string UnitScales;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=2)]
        public string UnitWeight;
        
        public FixedWeightRequest() {
        }
        
        public FixedWeightRequest(TestingService.ServiceReference1.BrHeader BrHeader, string label, string UnitScales, string UnitWeight) {
            this.BrHeader = BrHeader;
            this.label = label;
            this.UnitScales = UnitScales;
            this.UnitWeight = UnitWeight;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FixedWeightResponse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class FixedWeightResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public string FixedWeightResult;
        
        public FixedWeightResponse() {
        }
        
        public FixedWeightResponse(string FixedWeightResult) {
            this.FixedWeightResult = FixedWeightResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test_Connect", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class Test_ConnectRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="WebSDataBrCode")]
        public TestingService.ServiceReference1.BrHeader BrHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public string message;
        
        public Test_ConnectRequest() {
        }
        
        public Test_ConnectRequest(TestingService.ServiceReference1.BrHeader BrHeader, string message) {
            this.BrHeader = BrHeader;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test_ConnectResponse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class Test_ConnectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public bool Test_ConnectResult;
        
        public Test_ConnectResponse() {
        }
        
        public Test_ConnectResponse(bool Test_ConnectResult) {
            this.Test_ConnectResult = Test_ConnectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test_Login", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class Test_LoginRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="WebSDataBrCode")]
        public TestingService.ServiceReference1.BrHeader BrHeader;
        
        public Test_LoginRequest() {
        }
        
        public Test_LoginRequest(TestingService.ServiceReference1.BrHeader BrHeader) {
            this.BrHeader = BrHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test_LoginResponse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class Test_LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public bool Test_LoginResult;
        
        public Test_LoginResponse() {
        }
        
        public Test_LoginResponse(bool Test_LoginResult) {
            this.Test_LoginResult = Test_LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POST_EU_LIST_Warehouse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class POST_EU_LIST_WarehouseRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="WebSDataBrCode")]
        public TestingService.ServiceReference1.BrHeader BrHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public string[] listEU;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=1)]
        public string Place;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TimeOperation;
        
        public POST_EU_LIST_WarehouseRequest() {
        }
        
        public POST_EU_LIST_WarehouseRequest(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string Place, System.Nullable<System.DateTime> TimeOperation) {
            this.BrHeader = BrHeader;
            this.listEU = listEU;
            this.Place = Place;
            this.TimeOperation = TimeOperation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POST_EU_LIST_WarehouseResponse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class POST_EU_LIST_WarehouseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public System.Data.DataTable POST_EU_LIST_WarehouseResult;
        
        public POST_EU_LIST_WarehouseResponse() {
        }
        
        public POST_EU_LIST_WarehouseResponse(System.Data.DataTable POST_EU_LIST_WarehouseResult) {
            this.POST_EU_LIST_WarehouseResult = POST_EU_LIST_WarehouseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POST_EU_TASK_MOVE", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class POST_EU_TASK_MOVERequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="WebSDataBrCode")]
        public TestingService.ServiceReference1.BrHeader BrHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public string[] listEU;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=1)]
        public string Place;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TimeOperation;
        
        public POST_EU_TASK_MOVERequest() {
        }
        
        public POST_EU_TASK_MOVERequest(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string Place, System.Nullable<System.DateTime> TimeOperation) {
            this.BrHeader = BrHeader;
            this.listEU = listEU;
            this.Place = Place;
            this.TimeOperation = TimeOperation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POST_EU_TASK_MOVEResponse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class POST_EU_TASK_MOVEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public System.Data.DataTable POST_EU_TASK_MOVEResult;
        
        public POST_EU_TASK_MOVEResponse() {
        }
        
        public POST_EU_TASK_MOVEResponse(System.Data.DataTable POST_EU_TASK_MOVEResult) {
            this.POST_EU_TASK_MOVEResult = POST_EU_TASK_MOVEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POST_EU_IN_AGR", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class POST_EU_IN_AGRRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="WebSDataBrCode")]
        public TestingService.ServiceReference1.BrHeader BrHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public string[] listEU;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=1)]
        public string Agr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TimeOperation;
        
        public POST_EU_IN_AGRRequest() {
        }
        
        public POST_EU_IN_AGRRequest(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string Agr, System.Nullable<System.DateTime> TimeOperation) {
            this.BrHeader = BrHeader;
            this.listEU = listEU;
            this.Agr = Agr;
            this.TimeOperation = TimeOperation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POST_EU_IN_AGRResponse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class POST_EU_IN_AGRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public System.Data.DataTable POST_EU_IN_AGRResult;
        
        public POST_EU_IN_AGRResponse() {
        }
        
        public POST_EU_IN_AGRResponse(System.Data.DataTable POST_EU_IN_AGRResult) {
            this.POST_EU_IN_AGRResult = POST_EU_IN_AGRResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POST_EU_LIST_SHIP", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class POST_EU_LIST_SHIPRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="WebSDataBrCode")]
        public TestingService.ServiceReference1.BrHeader BrHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public string[] listEU;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=1)]
        public string RZDN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TimeOperation;
        
        public POST_EU_LIST_SHIPRequest() {
        }
        
        public POST_EU_LIST_SHIPRequest(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string RZDN, System.Nullable<System.DateTime> TimeOperation) {
            this.BrHeader = BrHeader;
            this.listEU = listEU;
            this.RZDN = RZDN;
            this.TimeOperation = TimeOperation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POST_EU_LIST_SHIPResponse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class POST_EU_LIST_SHIPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public System.Data.DataTable POST_EU_LIST_SHIPResult;
        
        public POST_EU_LIST_SHIPResponse() {
        }
        
        public POST_EU_LIST_SHIPResponse(System.Data.DataTable POST_EU_LIST_SHIPResult) {
            this.POST_EU_LIST_SHIPResult = POST_EU_LIST_SHIPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POST_EU_LIST_RZDN_AGR", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class POST_EU_LIST_RZDN_AGRRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="WebSDataBrCode")]
        public TestingService.ServiceReference1.BrHeader BrHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public string[] listEU;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=1)]
        public string RZDN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TimeOperation;
        
        public POST_EU_LIST_RZDN_AGRRequest() {
        }
        
        public POST_EU_LIST_RZDN_AGRRequest(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string RZDN, System.Nullable<System.DateTime> TimeOperation) {
            this.BrHeader = BrHeader;
            this.listEU = listEU;
            this.RZDN = RZDN;
            this.TimeOperation = TimeOperation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POST_EU_LIST_RZDN_AGRResponse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class POST_EU_LIST_RZDN_AGRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public System.Data.DataTable POST_EU_LIST_RZDN_AGRResult;
        
        public POST_EU_LIST_RZDN_AGRResponse() {
        }
        
        public POST_EU_LIST_RZDN_AGRResponse(System.Data.DataTable POST_EU_LIST_RZDN_AGRResult) {
            this.POST_EU_LIST_RZDN_AGRResult = POST_EU_LIST_RZDN_AGRResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POST_EU_LIST_INVERT_MX", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class POST_EU_LIST_INVERT_MXRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="WebSDataBrCode")]
        public TestingService.ServiceReference1.BrHeader BrHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public string[] listEU;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=1)]
        public string RZDN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=2)]
        public string MX_LABEL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TimeOperation;
        
        public POST_EU_LIST_INVERT_MXRequest() {
        }
        
        public POST_EU_LIST_INVERT_MXRequest(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string RZDN, string MX_LABEL, System.Nullable<System.DateTime> TimeOperation) {
            this.BrHeader = BrHeader;
            this.listEU = listEU;
            this.RZDN = RZDN;
            this.MX_LABEL = MX_LABEL;
            this.TimeOperation = TimeOperation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POST_EU_LIST_INVERT_MXResponse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class POST_EU_LIST_INVERT_MXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public System.Data.DataTable POST_EU_LIST_INVERT_MXResult;
        
        public POST_EU_LIST_INVERT_MXResponse() {
        }
        
        public POST_EU_LIST_INVERT_MXResponse(System.Data.DataTable POST_EU_LIST_INVERT_MXResult) {
            this.POST_EU_LIST_INVERT_MXResult = POST_EU_LIST_INVERT_MXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataBase_Clone_SQLiteZipFile", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class DataBase_Clone_SQLiteZipFileRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="WebSDataBrCode")]
        public TestingService.ServiceReference1.BrHeader BrHeader;
        
        public DataBase_Clone_SQLiteZipFileRequest() {
        }
        
        public DataBase_Clone_SQLiteZipFileRequest(TestingService.ServiceReference1.BrHeader BrHeader) {
            this.BrHeader = BrHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataBase_Clone_SQLiteZipFileResponse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class DataBase_Clone_SQLiteZipFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DataBase_Clone_SQLiteZipFileResult;
        
        public DataBase_Clone_SQLiteZipFileResponse() {
        }
        
        public DataBase_Clone_SQLiteZipFileResponse(byte[] DataBase_Clone_SQLiteZipFileResult) {
            this.DataBase_Clone_SQLiteZipFileResult = DataBase_Clone_SQLiteZipFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="System_Get_Release", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class System_Get_ReleaseRequest {
        
        public System_Get_ReleaseRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="System_Get_ReleaseResponse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class System_Get_ReleaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] System_Get_ReleaseResult;
        
        public System_Get_ReleaseResponse() {
        }
        
        public System_Get_ReleaseResponse(byte[] System_Get_ReleaseResult) {
            this.System_Get_ReleaseResult = System_Get_ReleaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestLog", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class TestLogRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="WebSDataBrCode")]
        public TestingService.ServiceReference1.BrHeader BrHeader;
        
        public TestLogRequest() {
        }
        
        public TestLogRequest(TestingService.ServiceReference1.BrHeader BrHeader) {
            this.BrHeader = BrHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestLogResponse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class TestLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public string TestLogResult;
        
        public TestLogResponse() {
        }
        
        public TestLogResponse(string TestLogResult) {
            this.TestLogResult = TestLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SAVE_LOG_TSD_ZIP", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class SAVE_LOG_TSD_ZIPRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="WebSDataBrCode")]
        public TestingService.ServiceReference1.BrHeader BrHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] result;
        
        public SAVE_LOG_TSD_ZIPRequest() {
        }
        
        public SAVE_LOG_TSD_ZIPRequest(TestingService.ServiceReference1.BrHeader BrHeader, byte[] result) {
            this.BrHeader = BrHeader;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SAVE_LOG_TSD_ZIPResponse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class SAVE_LOG_TSD_ZIPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public bool SAVE_LOG_TSD_ZIPResult;
        
        public SAVE_LOG_TSD_ZIPResponse() {
        }
        
        public SAVE_LOG_TSD_ZIPResponse(bool SAVE_LOG_TSD_ZIPResult) {
            this.SAVE_LOG_TSD_ZIPResult = SAVE_LOG_TSD_ZIPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CHECK_CLIENT_VERSION", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class CHECK_CLIENT_VERSIONRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="WebSDataBrCode")]
        public TestingService.ServiceReference1.BrHeader BrHeader;
        
        public CHECK_CLIENT_VERSIONRequest() {
        }
        
        public CHECK_CLIENT_VERSIONRequest(TestingService.ServiceReference1.BrHeader BrHeader) {
            this.BrHeader = BrHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CHECK_CLIENT_VERSIONResponse", WrapperNamespace="WebSDataBrCode", IsWrapped=true)]
    public partial class CHECK_CLIENT_VERSIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="WebSDataBrCode", Order=0)]
        public string CHECK_CLIENT_VERSIONResult;
        
        public CHECK_CLIENT_VERSIONResponse() {
        }
        
        public CHECK_CLIENT_VERSIONResponse(string CHECK_CLIENT_VERSIONResult) {
            this.CHECK_CLIENT_VERSIONResult = CHECK_CLIENT_VERSIONResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebSDataBrCodeSoapChannel : TestingService.ServiceReference1.WebSDataBrCodeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebSDataBrCodeSoapClient : System.ServiceModel.ClientBase<TestingService.ServiceReference1.WebSDataBrCodeSoap>, TestingService.ServiceReference1.WebSDataBrCodeSoap {
        
        public WebSDataBrCodeSoapClient() {
        }
        
        public WebSDataBrCodeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebSDataBrCodeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSDataBrCodeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSDataBrCodeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingService.ServiceReference1.GetServerDataTimeResponse TestingService.ServiceReference1.WebSDataBrCodeSoap.GetServerDataTime(TestingService.ServiceReference1.GetServerDataTimeRequest request) {
            return base.Channel.GetServerDataTime(request);
        }
        
        public System.DateTime GetServerDataTime(TestingService.ServiceReference1.BrHeader BrHeader) {
            TestingService.ServiceReference1.GetServerDataTimeRequest inValue = new TestingService.ServiceReference1.GetServerDataTimeRequest();
            inValue.BrHeader = BrHeader;
            TestingService.ServiceReference1.GetServerDataTimeResponse retVal = ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).GetServerDataTime(inValue);
            return retVal.GetServerDataTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.GetServerDataTimeResponse> TestingService.ServiceReference1.WebSDataBrCodeSoap.GetServerDataTimeAsync(TestingService.ServiceReference1.GetServerDataTimeRequest request) {
            return base.Channel.GetServerDataTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingService.ServiceReference1.GetServerDataTimeResponse> GetServerDataTimeAsync(TestingService.ServiceReference1.BrHeader BrHeader) {
            TestingService.ServiceReference1.GetServerDataTimeRequest inValue = new TestingService.ServiceReference1.GetServerDataTimeRequest();
            inValue.BrHeader = BrHeader;
            return ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).GetServerDataTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingService.ServiceReference1.FixedWeightResponse TestingService.ServiceReference1.WebSDataBrCodeSoap.FixedWeight(TestingService.ServiceReference1.FixedWeightRequest request) {
            return base.Channel.FixedWeight(request);
        }
        
        public string FixedWeight(TestingService.ServiceReference1.BrHeader BrHeader, string label, string UnitScales, string UnitWeight) {
            TestingService.ServiceReference1.FixedWeightRequest inValue = new TestingService.ServiceReference1.FixedWeightRequest();
            inValue.BrHeader = BrHeader;
            inValue.label = label;
            inValue.UnitScales = UnitScales;
            inValue.UnitWeight = UnitWeight;
            TestingService.ServiceReference1.FixedWeightResponse retVal = ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).FixedWeight(inValue);
            return retVal.FixedWeightResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.FixedWeightResponse> TestingService.ServiceReference1.WebSDataBrCodeSoap.FixedWeightAsync(TestingService.ServiceReference1.FixedWeightRequest request) {
            return base.Channel.FixedWeightAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingService.ServiceReference1.FixedWeightResponse> FixedWeightAsync(TestingService.ServiceReference1.BrHeader BrHeader, string label, string UnitScales, string UnitWeight) {
            TestingService.ServiceReference1.FixedWeightRequest inValue = new TestingService.ServiceReference1.FixedWeightRequest();
            inValue.BrHeader = BrHeader;
            inValue.label = label;
            inValue.UnitScales = UnitScales;
            inValue.UnitWeight = UnitWeight;
            return ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).FixedWeightAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingService.ServiceReference1.Test_ConnectResponse TestingService.ServiceReference1.WebSDataBrCodeSoap.Test_Connect(TestingService.ServiceReference1.Test_ConnectRequest request) {
            return base.Channel.Test_Connect(request);
        }
        
        public bool Test_Connect(TestingService.ServiceReference1.BrHeader BrHeader, string message) {
            TestingService.ServiceReference1.Test_ConnectRequest inValue = new TestingService.ServiceReference1.Test_ConnectRequest();
            inValue.BrHeader = BrHeader;
            inValue.message = message;
            TestingService.ServiceReference1.Test_ConnectResponse retVal = ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).Test_Connect(inValue);
            return retVal.Test_ConnectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.Test_ConnectResponse> TestingService.ServiceReference1.WebSDataBrCodeSoap.Test_ConnectAsync(TestingService.ServiceReference1.Test_ConnectRequest request) {
            return base.Channel.Test_ConnectAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingService.ServiceReference1.Test_ConnectResponse> Test_ConnectAsync(TestingService.ServiceReference1.BrHeader BrHeader, string message) {
            TestingService.ServiceReference1.Test_ConnectRequest inValue = new TestingService.ServiceReference1.Test_ConnectRequest();
            inValue.BrHeader = BrHeader;
            inValue.message = message;
            return ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).Test_ConnectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingService.ServiceReference1.Test_LoginResponse TestingService.ServiceReference1.WebSDataBrCodeSoap.Test_Login(TestingService.ServiceReference1.Test_LoginRequest request) {
            return base.Channel.Test_Login(request);
        }
        
        public bool Test_Login(TestingService.ServiceReference1.BrHeader BrHeader) {
            TestingService.ServiceReference1.Test_LoginRequest inValue = new TestingService.ServiceReference1.Test_LoginRequest();
            inValue.BrHeader = BrHeader;
            TestingService.ServiceReference1.Test_LoginResponse retVal = ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).Test_Login(inValue);
            return retVal.Test_LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.Test_LoginResponse> TestingService.ServiceReference1.WebSDataBrCodeSoap.Test_LoginAsync(TestingService.ServiceReference1.Test_LoginRequest request) {
            return base.Channel.Test_LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingService.ServiceReference1.Test_LoginResponse> Test_LoginAsync(TestingService.ServiceReference1.BrHeader BrHeader) {
            TestingService.ServiceReference1.Test_LoginRequest inValue = new TestingService.ServiceReference1.Test_LoginRequest();
            inValue.BrHeader = BrHeader;
            return ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).Test_LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingService.ServiceReference1.POST_EU_LIST_WarehouseResponse TestingService.ServiceReference1.WebSDataBrCodeSoap.POST_EU_LIST_Warehouse(TestingService.ServiceReference1.POST_EU_LIST_WarehouseRequest request) {
            return base.Channel.POST_EU_LIST_Warehouse(request);
        }
        
        public System.Data.DataTable POST_EU_LIST_Warehouse(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string Place, System.Nullable<System.DateTime> TimeOperation) {
            TestingService.ServiceReference1.POST_EU_LIST_WarehouseRequest inValue = new TestingService.ServiceReference1.POST_EU_LIST_WarehouseRequest();
            inValue.BrHeader = BrHeader;
            inValue.listEU = listEU;
            inValue.Place = Place;
            inValue.TimeOperation = TimeOperation;
            TestingService.ServiceReference1.POST_EU_LIST_WarehouseResponse retVal = ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).POST_EU_LIST_Warehouse(inValue);
            return retVal.POST_EU_LIST_WarehouseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_LIST_WarehouseResponse> TestingService.ServiceReference1.WebSDataBrCodeSoap.POST_EU_LIST_WarehouseAsync(TestingService.ServiceReference1.POST_EU_LIST_WarehouseRequest request) {
            return base.Channel.POST_EU_LIST_WarehouseAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_LIST_WarehouseResponse> POST_EU_LIST_WarehouseAsync(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string Place, System.Nullable<System.DateTime> TimeOperation) {
            TestingService.ServiceReference1.POST_EU_LIST_WarehouseRequest inValue = new TestingService.ServiceReference1.POST_EU_LIST_WarehouseRequest();
            inValue.BrHeader = BrHeader;
            inValue.listEU = listEU;
            inValue.Place = Place;
            inValue.TimeOperation = TimeOperation;
            return ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).POST_EU_LIST_WarehouseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingService.ServiceReference1.POST_EU_TASK_MOVEResponse TestingService.ServiceReference1.WebSDataBrCodeSoap.POST_EU_TASK_MOVE(TestingService.ServiceReference1.POST_EU_TASK_MOVERequest request) {
            return base.Channel.POST_EU_TASK_MOVE(request);
        }
        
        public System.Data.DataTable POST_EU_TASK_MOVE(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string Place, System.Nullable<System.DateTime> TimeOperation) {
            TestingService.ServiceReference1.POST_EU_TASK_MOVERequest inValue = new TestingService.ServiceReference1.POST_EU_TASK_MOVERequest();
            inValue.BrHeader = BrHeader;
            inValue.listEU = listEU;
            inValue.Place = Place;
            inValue.TimeOperation = TimeOperation;
            TestingService.ServiceReference1.POST_EU_TASK_MOVEResponse retVal = ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).POST_EU_TASK_MOVE(inValue);
            return retVal.POST_EU_TASK_MOVEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_TASK_MOVEResponse> TestingService.ServiceReference1.WebSDataBrCodeSoap.POST_EU_TASK_MOVEAsync(TestingService.ServiceReference1.POST_EU_TASK_MOVERequest request) {
            return base.Channel.POST_EU_TASK_MOVEAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_TASK_MOVEResponse> POST_EU_TASK_MOVEAsync(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string Place, System.Nullable<System.DateTime> TimeOperation) {
            TestingService.ServiceReference1.POST_EU_TASK_MOVERequest inValue = new TestingService.ServiceReference1.POST_EU_TASK_MOVERequest();
            inValue.BrHeader = BrHeader;
            inValue.listEU = listEU;
            inValue.Place = Place;
            inValue.TimeOperation = TimeOperation;
            return ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).POST_EU_TASK_MOVEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingService.ServiceReference1.POST_EU_IN_AGRResponse TestingService.ServiceReference1.WebSDataBrCodeSoap.POST_EU_IN_AGR(TestingService.ServiceReference1.POST_EU_IN_AGRRequest request) {
            return base.Channel.POST_EU_IN_AGR(request);
        }
        
        public System.Data.DataTable POST_EU_IN_AGR(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string Agr, System.Nullable<System.DateTime> TimeOperation) {
            TestingService.ServiceReference1.POST_EU_IN_AGRRequest inValue = new TestingService.ServiceReference1.POST_EU_IN_AGRRequest();
            inValue.BrHeader = BrHeader;
            inValue.listEU = listEU;
            inValue.Agr = Agr;
            inValue.TimeOperation = TimeOperation;
            TestingService.ServiceReference1.POST_EU_IN_AGRResponse retVal = ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).POST_EU_IN_AGR(inValue);
            return retVal.POST_EU_IN_AGRResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_IN_AGRResponse> TestingService.ServiceReference1.WebSDataBrCodeSoap.POST_EU_IN_AGRAsync(TestingService.ServiceReference1.POST_EU_IN_AGRRequest request) {
            return base.Channel.POST_EU_IN_AGRAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_IN_AGRResponse> POST_EU_IN_AGRAsync(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string Agr, System.Nullable<System.DateTime> TimeOperation) {
            TestingService.ServiceReference1.POST_EU_IN_AGRRequest inValue = new TestingService.ServiceReference1.POST_EU_IN_AGRRequest();
            inValue.BrHeader = BrHeader;
            inValue.listEU = listEU;
            inValue.Agr = Agr;
            inValue.TimeOperation = TimeOperation;
            return ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).POST_EU_IN_AGRAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingService.ServiceReference1.POST_EU_LIST_SHIPResponse TestingService.ServiceReference1.WebSDataBrCodeSoap.POST_EU_LIST_SHIP(TestingService.ServiceReference1.POST_EU_LIST_SHIPRequest request) {
            return base.Channel.POST_EU_LIST_SHIP(request);
        }
        
        public System.Data.DataTable POST_EU_LIST_SHIP(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string RZDN, System.Nullable<System.DateTime> TimeOperation) {
            TestingService.ServiceReference1.POST_EU_LIST_SHIPRequest inValue = new TestingService.ServiceReference1.POST_EU_LIST_SHIPRequest();
            inValue.BrHeader = BrHeader;
            inValue.listEU = listEU;
            inValue.RZDN = RZDN;
            inValue.TimeOperation = TimeOperation;
            TestingService.ServiceReference1.POST_EU_LIST_SHIPResponse retVal = ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).POST_EU_LIST_SHIP(inValue);
            return retVal.POST_EU_LIST_SHIPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_LIST_SHIPResponse> TestingService.ServiceReference1.WebSDataBrCodeSoap.POST_EU_LIST_SHIPAsync(TestingService.ServiceReference1.POST_EU_LIST_SHIPRequest request) {
            return base.Channel.POST_EU_LIST_SHIPAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_LIST_SHIPResponse> POST_EU_LIST_SHIPAsync(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string RZDN, System.Nullable<System.DateTime> TimeOperation) {
            TestingService.ServiceReference1.POST_EU_LIST_SHIPRequest inValue = new TestingService.ServiceReference1.POST_EU_LIST_SHIPRequest();
            inValue.BrHeader = BrHeader;
            inValue.listEU = listEU;
            inValue.RZDN = RZDN;
            inValue.TimeOperation = TimeOperation;
            return ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).POST_EU_LIST_SHIPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingService.ServiceReference1.POST_EU_LIST_RZDN_AGRResponse TestingService.ServiceReference1.WebSDataBrCodeSoap.POST_EU_LIST_RZDN_AGR(TestingService.ServiceReference1.POST_EU_LIST_RZDN_AGRRequest request) {
            return base.Channel.POST_EU_LIST_RZDN_AGR(request);
        }
        
        public System.Data.DataTable POST_EU_LIST_RZDN_AGR(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string RZDN, System.Nullable<System.DateTime> TimeOperation) {
            TestingService.ServiceReference1.POST_EU_LIST_RZDN_AGRRequest inValue = new TestingService.ServiceReference1.POST_EU_LIST_RZDN_AGRRequest();
            inValue.BrHeader = BrHeader;
            inValue.listEU = listEU;
            inValue.RZDN = RZDN;
            inValue.TimeOperation = TimeOperation;
            TestingService.ServiceReference1.POST_EU_LIST_RZDN_AGRResponse retVal = ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).POST_EU_LIST_RZDN_AGR(inValue);
            return retVal.POST_EU_LIST_RZDN_AGRResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_LIST_RZDN_AGRResponse> TestingService.ServiceReference1.WebSDataBrCodeSoap.POST_EU_LIST_RZDN_AGRAsync(TestingService.ServiceReference1.POST_EU_LIST_RZDN_AGRRequest request) {
            return base.Channel.POST_EU_LIST_RZDN_AGRAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_LIST_RZDN_AGRResponse> POST_EU_LIST_RZDN_AGRAsync(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string RZDN, System.Nullable<System.DateTime> TimeOperation) {
            TestingService.ServiceReference1.POST_EU_LIST_RZDN_AGRRequest inValue = new TestingService.ServiceReference1.POST_EU_LIST_RZDN_AGRRequest();
            inValue.BrHeader = BrHeader;
            inValue.listEU = listEU;
            inValue.RZDN = RZDN;
            inValue.TimeOperation = TimeOperation;
            return ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).POST_EU_LIST_RZDN_AGRAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingService.ServiceReference1.POST_EU_LIST_INVERT_MXResponse TestingService.ServiceReference1.WebSDataBrCodeSoap.POST_EU_LIST_INVERT_MX(TestingService.ServiceReference1.POST_EU_LIST_INVERT_MXRequest request) {
            return base.Channel.POST_EU_LIST_INVERT_MX(request);
        }
        
        public System.Data.DataTable POST_EU_LIST_INVERT_MX(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string RZDN, string MX_LABEL, System.Nullable<System.DateTime> TimeOperation) {
            TestingService.ServiceReference1.POST_EU_LIST_INVERT_MXRequest inValue = new TestingService.ServiceReference1.POST_EU_LIST_INVERT_MXRequest();
            inValue.BrHeader = BrHeader;
            inValue.listEU = listEU;
            inValue.RZDN = RZDN;
            inValue.MX_LABEL = MX_LABEL;
            inValue.TimeOperation = TimeOperation;
            TestingService.ServiceReference1.POST_EU_LIST_INVERT_MXResponse retVal = ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).POST_EU_LIST_INVERT_MX(inValue);
            return retVal.POST_EU_LIST_INVERT_MXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_LIST_INVERT_MXResponse> TestingService.ServiceReference1.WebSDataBrCodeSoap.POST_EU_LIST_INVERT_MXAsync(TestingService.ServiceReference1.POST_EU_LIST_INVERT_MXRequest request) {
            return base.Channel.POST_EU_LIST_INVERT_MXAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingService.ServiceReference1.POST_EU_LIST_INVERT_MXResponse> POST_EU_LIST_INVERT_MXAsync(TestingService.ServiceReference1.BrHeader BrHeader, string[] listEU, string RZDN, string MX_LABEL, System.Nullable<System.DateTime> TimeOperation) {
            TestingService.ServiceReference1.POST_EU_LIST_INVERT_MXRequest inValue = new TestingService.ServiceReference1.POST_EU_LIST_INVERT_MXRequest();
            inValue.BrHeader = BrHeader;
            inValue.listEU = listEU;
            inValue.RZDN = RZDN;
            inValue.MX_LABEL = MX_LABEL;
            inValue.TimeOperation = TimeOperation;
            return ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).POST_EU_LIST_INVERT_MXAsync(inValue);
        }
        
        public System.Data.DataTable GetLogTSD() {
            return base.Channel.GetLogTSD();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetLogTSDAsync() {
            return base.Channel.GetLogTSDAsync();
        }
        
        public System.Data.DataTable GetLogTSDOnline() {
            return base.Channel.GetLogTSDOnline();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetLogTSDOnlineAsync() {
            return base.Channel.GetLogTSDOnlineAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingService.ServiceReference1.DataBase_Clone_SQLiteZipFileResponse TestingService.ServiceReference1.WebSDataBrCodeSoap.DataBase_Clone_SQLiteZipFile(TestingService.ServiceReference1.DataBase_Clone_SQLiteZipFileRequest request) {
            return base.Channel.DataBase_Clone_SQLiteZipFile(request);
        }
        
        public byte[] DataBase_Clone_SQLiteZipFile(TestingService.ServiceReference1.BrHeader BrHeader) {
            TestingService.ServiceReference1.DataBase_Clone_SQLiteZipFileRequest inValue = new TestingService.ServiceReference1.DataBase_Clone_SQLiteZipFileRequest();
            inValue.BrHeader = BrHeader;
            TestingService.ServiceReference1.DataBase_Clone_SQLiteZipFileResponse retVal = ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).DataBase_Clone_SQLiteZipFile(inValue);
            return retVal.DataBase_Clone_SQLiteZipFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.DataBase_Clone_SQLiteZipFileResponse> TestingService.ServiceReference1.WebSDataBrCodeSoap.DataBase_Clone_SQLiteZipFileAsync(TestingService.ServiceReference1.DataBase_Clone_SQLiteZipFileRequest request) {
            return base.Channel.DataBase_Clone_SQLiteZipFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingService.ServiceReference1.DataBase_Clone_SQLiteZipFileResponse> DataBase_Clone_SQLiteZipFileAsync(TestingService.ServiceReference1.BrHeader BrHeader) {
            TestingService.ServiceReference1.DataBase_Clone_SQLiteZipFileRequest inValue = new TestingService.ServiceReference1.DataBase_Clone_SQLiteZipFileRequest();
            inValue.BrHeader = BrHeader;
            return ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).DataBase_Clone_SQLiteZipFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingService.ServiceReference1.System_Get_ReleaseResponse TestingService.ServiceReference1.WebSDataBrCodeSoap.System_Get_Release(TestingService.ServiceReference1.System_Get_ReleaseRequest request) {
            return base.Channel.System_Get_Release(request);
        }
        
        public byte[] System_Get_Release() {
            TestingService.ServiceReference1.System_Get_ReleaseRequest inValue = new TestingService.ServiceReference1.System_Get_ReleaseRequest();
            TestingService.ServiceReference1.System_Get_ReleaseResponse retVal = ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).System_Get_Release(inValue);
            return retVal.System_Get_ReleaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.System_Get_ReleaseResponse> TestingService.ServiceReference1.WebSDataBrCodeSoap.System_Get_ReleaseAsync(TestingService.ServiceReference1.System_Get_ReleaseRequest request) {
            return base.Channel.System_Get_ReleaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingService.ServiceReference1.System_Get_ReleaseResponse> System_Get_ReleaseAsync() {
            TestingService.ServiceReference1.System_Get_ReleaseRequest inValue = new TestingService.ServiceReference1.System_Get_ReleaseRequest();
            return ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).System_Get_ReleaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingService.ServiceReference1.TestLogResponse TestingService.ServiceReference1.WebSDataBrCodeSoap.TestLog(TestingService.ServiceReference1.TestLogRequest request) {
            return base.Channel.TestLog(request);
        }
        
        public string TestLog(TestingService.ServiceReference1.BrHeader BrHeader) {
            TestingService.ServiceReference1.TestLogRequest inValue = new TestingService.ServiceReference1.TestLogRequest();
            inValue.BrHeader = BrHeader;
            TestingService.ServiceReference1.TestLogResponse retVal = ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).TestLog(inValue);
            return retVal.TestLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.TestLogResponse> TestingService.ServiceReference1.WebSDataBrCodeSoap.TestLogAsync(TestingService.ServiceReference1.TestLogRequest request) {
            return base.Channel.TestLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingService.ServiceReference1.TestLogResponse> TestLogAsync(TestingService.ServiceReference1.BrHeader BrHeader) {
            TestingService.ServiceReference1.TestLogRequest inValue = new TestingService.ServiceReference1.TestLogRequest();
            inValue.BrHeader = BrHeader;
            return ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).TestLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingService.ServiceReference1.SAVE_LOG_TSD_ZIPResponse TestingService.ServiceReference1.WebSDataBrCodeSoap.SAVE_LOG_TSD_ZIP(TestingService.ServiceReference1.SAVE_LOG_TSD_ZIPRequest request) {
            return base.Channel.SAVE_LOG_TSD_ZIP(request);
        }
        
        public bool SAVE_LOG_TSD_ZIP(TestingService.ServiceReference1.BrHeader BrHeader, byte[] result) {
            TestingService.ServiceReference1.SAVE_LOG_TSD_ZIPRequest inValue = new TestingService.ServiceReference1.SAVE_LOG_TSD_ZIPRequest();
            inValue.BrHeader = BrHeader;
            inValue.result = result;
            TestingService.ServiceReference1.SAVE_LOG_TSD_ZIPResponse retVal = ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).SAVE_LOG_TSD_ZIP(inValue);
            return retVal.SAVE_LOG_TSD_ZIPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.SAVE_LOG_TSD_ZIPResponse> TestingService.ServiceReference1.WebSDataBrCodeSoap.SAVE_LOG_TSD_ZIPAsync(TestingService.ServiceReference1.SAVE_LOG_TSD_ZIPRequest request) {
            return base.Channel.SAVE_LOG_TSD_ZIPAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingService.ServiceReference1.SAVE_LOG_TSD_ZIPResponse> SAVE_LOG_TSD_ZIPAsync(TestingService.ServiceReference1.BrHeader BrHeader, byte[] result) {
            TestingService.ServiceReference1.SAVE_LOG_TSD_ZIPRequest inValue = new TestingService.ServiceReference1.SAVE_LOG_TSD_ZIPRequest();
            inValue.BrHeader = BrHeader;
            inValue.result = result;
            return ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).SAVE_LOG_TSD_ZIPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingService.ServiceReference1.CHECK_CLIENT_VERSIONResponse TestingService.ServiceReference1.WebSDataBrCodeSoap.CHECK_CLIENT_VERSION(TestingService.ServiceReference1.CHECK_CLIENT_VERSIONRequest request) {
            return base.Channel.CHECK_CLIENT_VERSION(request);
        }
        
        public string CHECK_CLIENT_VERSION(TestingService.ServiceReference1.BrHeader BrHeader) {
            TestingService.ServiceReference1.CHECK_CLIENT_VERSIONRequest inValue = new TestingService.ServiceReference1.CHECK_CLIENT_VERSIONRequest();
            inValue.BrHeader = BrHeader;
            TestingService.ServiceReference1.CHECK_CLIENT_VERSIONResponse retVal = ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).CHECK_CLIENT_VERSION(inValue);
            return retVal.CHECK_CLIENT_VERSIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingService.ServiceReference1.CHECK_CLIENT_VERSIONResponse> TestingService.ServiceReference1.WebSDataBrCodeSoap.CHECK_CLIENT_VERSIONAsync(TestingService.ServiceReference1.CHECK_CLIENT_VERSIONRequest request) {
            return base.Channel.CHECK_CLIENT_VERSIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingService.ServiceReference1.CHECK_CLIENT_VERSIONResponse> CHECK_CLIENT_VERSIONAsync(TestingService.ServiceReference1.BrHeader BrHeader) {
            TestingService.ServiceReference1.CHECK_CLIENT_VERSIONRequest inValue = new TestingService.ServiceReference1.CHECK_CLIENT_VERSIONRequest();
            inValue.BrHeader = BrHeader;
            return ((TestingService.ServiceReference1.WebSDataBrCodeSoap)(this)).CHECK_CLIENT_VERSIONAsync(inValue);
        }
    }
}
