//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.5420
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.CompactFramework.Design.Data, версия: 2.0.50727.5420.
// 
namespace DataBarCode.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebSDataBrCodeSoap", Namespace="WebSDataBrCode")]
    public partial class WebSDataBrCode : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private BrHeader brHeaderValueField;
        
        /// <remarks/>
        public WebSDataBrCode() {
            this.Url = "http://192.168.80.15:4607/WebSDataBrCode.asmx";
        }
        
        public BrHeader BrHeaderValue {
            get {
                return this.brHeaderValueField;
            }
            set {
                this.brHeaderValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BrHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/GetServerDataTime", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime GetServerDataTime() {
            object[] results = this.Invoke("GetServerDataTime", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetServerDataTime(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetServerDataTime", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.DateTime EndGetServerDataTime(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BrHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/FixedWeight", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FixedWeight(string label, string UnitScales, string UnitWeight) {
            object[] results = this.Invoke("FixedWeight", new object[] {
                        label,
                        UnitScales,
                        UnitWeight});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFixedWeight(string label, string UnitScales, string UnitWeight, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FixedWeight", new object[] {
                        label,
                        UnitScales,
                        UnitWeight}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndFixedWeight(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BrHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/Test_Connect", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Test_Connect(string message) {
            object[] results = this.Invoke("Test_Connect", new object[] {
                        message});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTest_Connect(string message, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Test_Connect", new object[] {
                        message}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndTest_Connect(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BrHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/Test_Login", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Test_Login() {
            object[] results = this.Invoke("Test_Login", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTest_Login(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Test_Login", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndTest_Login(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BrHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/POST_EU_LIST_Warehouse", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable POST_EU_LIST_Warehouse(string[] listEU, string Place, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> TimeOperation) {
            object[] results = this.Invoke("POST_EU_LIST_Warehouse", new object[] {
                        listEU,
                        Place,
                        TimeOperation});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPOST_EU_LIST_Warehouse(string[] listEU, string Place, System.Nullable<System.DateTime> TimeOperation, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("POST_EU_LIST_Warehouse", new object[] {
                        listEU,
                        Place,
                        TimeOperation}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndPOST_EU_LIST_Warehouse(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BrHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/POST_EU_TASK_MOVE", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable POST_EU_TASK_MOVE(string[] listEU, string Place, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> TimeOperation) {
            object[] results = this.Invoke("POST_EU_TASK_MOVE", new object[] {
                        listEU,
                        Place,
                        TimeOperation});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPOST_EU_TASK_MOVE(string[] listEU, string Place, System.Nullable<System.DateTime> TimeOperation, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("POST_EU_TASK_MOVE", new object[] {
                        listEU,
                        Place,
                        TimeOperation}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndPOST_EU_TASK_MOVE(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BrHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/POST_EU_IN_AGR", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable POST_EU_IN_AGR(string[] listEU, string Agr, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> TimeOperation) {
            object[] results = this.Invoke("POST_EU_IN_AGR", new object[] {
                        listEU,
                        Agr,
                        TimeOperation});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPOST_EU_IN_AGR(string[] listEU, string Agr, System.Nullable<System.DateTime> TimeOperation, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("POST_EU_IN_AGR", new object[] {
                        listEU,
                        Agr,
                        TimeOperation}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndPOST_EU_IN_AGR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BrHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/POST_EU_LIST_SHIP", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable POST_EU_LIST_SHIP(string[] listEU, string RZDN, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> TimeOperation) {
            object[] results = this.Invoke("POST_EU_LIST_SHIP", new object[] {
                        listEU,
                        RZDN,
                        TimeOperation});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPOST_EU_LIST_SHIP(string[] listEU, string RZDN, System.Nullable<System.DateTime> TimeOperation, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("POST_EU_LIST_SHIP", new object[] {
                        listEU,
                        RZDN,
                        TimeOperation}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndPOST_EU_LIST_SHIP(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BrHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/POST_EU_LIST_RZDN_AGR", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable POST_EU_LIST_RZDN_AGR(string[] listEU, string RZDN, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> TimeOperation) {
            object[] results = this.Invoke("POST_EU_LIST_RZDN_AGR", new object[] {
                        listEU,
                        RZDN,
                        TimeOperation});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPOST_EU_LIST_RZDN_AGR(string[] listEU, string RZDN, System.Nullable<System.DateTime> TimeOperation, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("POST_EU_LIST_RZDN_AGR", new object[] {
                        listEU,
                        RZDN,
                        TimeOperation}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndPOST_EU_LIST_RZDN_AGR(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BrHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/POST_EU_LIST_INVERT_MX", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable POST_EU_LIST_INVERT_MX(string[] listEU, string RZDN, string MX_LABEL, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> TimeOperation) {
            object[] results = this.Invoke("POST_EU_LIST_INVERT_MX", new object[] {
                        listEU,
                        RZDN,
                        MX_LABEL,
                        TimeOperation});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPOST_EU_LIST_INVERT_MX(string[] listEU, string RZDN, string MX_LABEL, System.Nullable<System.DateTime> TimeOperation, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("POST_EU_LIST_INVERT_MX", new object[] {
                        listEU,
                        RZDN,
                        MX_LABEL,
                        TimeOperation}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndPOST_EU_LIST_INVERT_MX(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/GetLogTSD", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetLogTSD() {
            object[] results = this.Invoke("GetLogTSD", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLogTSD(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLogTSD", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetLogTSD(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/GetLogTSDOnline", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetLogTSDOnline() {
            object[] results = this.Invoke("GetLogTSDOnline", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLogTSDOnline(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLogTSDOnline", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetLogTSDOnline(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BrHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/DataBase_Clone_SQLiteZipFile", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DataBase_Clone_SQLiteZipFile() {
            object[] results = this.Invoke("DataBase_Clone_SQLiteZipFile", new object[0]);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDataBase_Clone_SQLiteZipFile(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DataBase_Clone_SQLiteZipFile", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndDataBase_Clone_SQLiteZipFile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/System_Get_Release", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] System_Get_Release() {
            object[] results = this.Invoke("System_Get_Release", new object[0]);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSystem_Get_Release(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("System_Get_Release", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndSystem_Get_Release(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BrHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/TestLog", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestLog() {
            object[] results = this.Invoke("TestLog", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTestLog(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TestLog", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndTestLog(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BrHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/SAVE_LOG_TSD_ZIP", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SAVE_LOG_TSD_ZIP([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] result) {
            object[] results = this.Invoke("SAVE_LOG_TSD_ZIP", new object[] {
                        result});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSAVE_LOG_TSD_ZIP(byte[] result, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SAVE_LOG_TSD_ZIP", new object[] {
                        result}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndSAVE_LOG_TSD_ZIP(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BrHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WebSDataBrCode/CHECK_CLIENT_VERSION", RequestNamespace="WebSDataBrCode", ResponseNamespace="WebSDataBrCode", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CHECK_CLIENT_VERSION() {
            object[] results = this.Invoke("CHECK_CLIENT_VERSION", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCHECK_CLIENT_VERSION(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CHECK_CLIENT_VERSION", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCHECK_CLIENT_VERSION(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="WebSDataBrCode")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="WebSDataBrCode", IsNullable=false)]
    public partial class BrHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string loginField;
        
        private string passwordField;
        
        private string macAdressField;
        
        private string dnsAdressField;
        
        private string clientVersionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string MacAdress {
            get {
                return this.macAdressField;
            }
            set {
                this.macAdressField = value;
            }
        }
        
        /// <remarks/>
        public string DnsAdress {
            get {
                return this.dnsAdressField;
            }
            set {
                this.dnsAdressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientVersion {
            get {
                return this.clientVersionField;
            }
            set {
                this.clientVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
}
